apiVersion: v1
kind: Service
metadata:
  name: PrivShield
  namespace: PrivShield
  labels:
    app: PrivShield
spec:
  type: ClusterIP
  selector:
    app: PrivShield
  ports:
    - name: http
      port: 8079
      targetPort: 8079
    - name: grpc
      port: 50051
      targetPort: 50051
